- alias: record cam0 movement
  trigger:
   platform: state
   entity_id: binary_sensor.aeotec_zw100_multisensor_6_sensor_3
   to: 'on'
  condition:
   condition: state
   entity_id: group.persons
   state: 'not_home'
  action:
   - service: shell_command.record_cam
     data:
      stream: 'rtsp://192.168.178.72:554/11'
      cam: 'cam0'
