- alias: Turn on study
  trigger:
    - platform: state
      entity_id: binary_sensor.zw100_multisensor_6_home_security_motion_detected_2
      to: 'on'
    - platform: state
      entity_id: sensor.rst_emu_slu
    - platform: state
      entity_id: binary_sensor.artificial_light
  condition:
    condition: template
    value_template: "
    {{
      is_state('group.persons','home') and
      is_state('binary_sensor.artificial_light','on') and 
      (is_state('input_text.last_movement','Study') or is_state('binary_sensor.zw100_multisensor_6_home_security_motion_detected_2','on')) and
      is_state('input_boolean.sleep_mode','off')
    }}"
  action:
    service: light.turn_on
    data:
      entity_id: light.study