- alias: Turn off study
  trigger:
   - platform: state
     entity_id: binary_sensor.rst_emu_smo
     to: 'off'
   - platform: numeric_state
     entity_id: sensor.rst_emu_slu
     above: 30
  action:
   service: light.turn_off
   data:
    entity_id: light.study