- alias: Turn off study
  trigger:
    - platform: state
      entity_id: binary_sensor.zw100_multisensor_6_home_security_motion_detected_2
      to: 'off'
      for:
        seconds: 20
    - platform: state
      entity_id: sensor.average_apartment_luminance
    - platform: state
      entity_id: input_text.last_movement
    - platform: state
      entity_id:
        - binary_sensor.artificial_light
  condition:
    - condition: template
      value_template: "
  {{
    is_state('binary_sensor.artificial_light','off') or 
    (not is_state('input_text.last_movement', 'Study') and is_state('binary_sensor.zw100_multisensor_6_home_security_motion_detected_2', 'off'))
  }}"  
  action:
    service: light.turn_off
    data_template:
      entity_id: light.study
      transition: >
            {% if states.switch.circadian_lighting_circadian_lighting.attributes["brightness"] | int >= 10 %}
              10
            {% else %}
              1
            {% endif %}