- alias: Turn on study
  trigger:
   - platform: state
     entity_id: binary_sensor.rst_emu_smo
     to: 'on'
  condition:
   - condition: state
     entity_id: group.persons
     state: 'home'
   - condition: numeric_state
     entity_id: sensor.rst_emu_slu
     below: 40
  action:
   service: light.turn_on
   data:
    entity_id: light.study