- alias: Set sleep mode
  trigger:
    - platform: state
      entity_id: input_boolean.sleep_mode
      to: 'on'
    - platform: state
      entity_id: input_number.night_purifier_favorite_level
  action:
    - service: xiaomi_miio.fan_set_favorite_level
      data_template:
        {"entity_id": "fan.xiaomi_miio_device","level":"{{states('input_number.night_purifier_favorite_level') | int}}"}