- alias: Set awake mode
  trigger:
    - platform: state
      entity_id: input_boolean.sleep_mode
    - platform: state
      entity_id: input_number.day_purifier_favorite_level
  condition:
    - condition: state
      entity_id:
        - input_boolean.sleep_mode
      state: "off"
  action:
    - service: xiaomi_miio.fan_set_favorite_level
      data_template:
        {
          "entity_id": "fan.xiaomi_miio_device",
          "level": "{{states('input_number.day_purifier_favorite_level') | int}}",
        }
