- alias: Set auto
  trigger:
   - platform: state
     entity_id: binary_sensor.sleep
     to: 'on'
  action:
    - service: fan.set_speed
      data:
        entity_id: 'fan.xiaomi_miio_device'
        speed: 'auto'