- alias: Turn on led when awake
  trigger:
   - platform: state
     entity_id: binary_sensor.sleep
     to: 'off'
  action:
    - service: fan.xiaomi_miio_set_led_on
      data:
        entity_id: "fan.xiaomi_miio_device"