- alias: Turn off led when sleep
  trigger:
   - platform: state
     entity_id: binary_sensor.sleep
     to: 'on'
  action:
    - service: xiaomi_miio.fan_set_led_off
      data:
        entity_id: "fan.xiaomi_miio_device"