- alias: Arm away if not home
  trigger:
   - platform: state
     entity_id: group.persons
     to: 'not_home'
  condition:
    condition: or
    conditions:
     - condition: state
       entity_id: alarm_control_panel.home_alarm
       state: disarmed
     - condition: state
       entity_id: alarm_control_panel.home_alarm
       state: pending
  action:
   service: alarm_control_panel.alarm_arm_away
   entity_id: alarm_control_panel.home_alarm
   data:
    code: !secret alarm_code