- alias: Disarm when home
  trigger:
   - platform: state
     entity_id: group.persons
     to: 'home'
  condition:
   - condition: state
     entity_id: alarm_control_panel.home_alarm
     state: armed_away
  action:
   service: alarm_control_panel.alarm_disarm
   entity_id: alarm_control_panel.home_alarm
   data:
    code: !secret alarm_code