- alias: Disarm when not asleep
  trigger:
   - platform: state
     entity_id: input_boolean.sleep_mode
     to: 'off'
  condition:
   - condition: state
     entity_id: alarm_control_panel.home_alarm
     state: armed_night
  action:
   service: alarm_control_panel.alarm_disarm
   entity_id: alarm_control_panel.home_alarm
   data:
    code: !secret alarm_code