- alias: Trigger alarm while armed away
  trigger:
   - platform: state
     entity_id: binary_sensor.rba_emu_smo
     to: 'on'
   - platform: state
     entity_id: binary_sensor.rbe_emu_smo
     to: 'on'
   - platform: state
     entity_id: binary_sensor.rha_edo
     to: 'on'
   - platform: state
     entity_id: binary_sensor.rha_emu_smo
     to: 'on'
   - platform: state
     entity_id: binary_sensor.rli_emu_00_smo
     to: 'on'
   - platform: state
     entity_id: binary_sensor.rli_emu_01_smo
     to: 'on'
   - platform: state
     entity_id: binary_sensor.rst_emu_smo
     to: 'on'
   - platform: state
     entity_id: binary_sensor.rto_emu_smo
     to: 'on'
  condition:
   - condition: state
     entity_id: alarm_control_panel.home_alarm
     state: armed_away
  action:
   - service: alarm_control_panel.alarm_trigger
     entity_id: alarm_control_panel.home_alarm
   - service: camera.snapshot
     data:
      entity_id: camera.hallway, camera.living_area
      filename: '/share/snapshots/{{ entity_id.entity_id }}.jpg'