homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret time_zone
  # Customization file
  customize: !include customize.yaml
  whitelist_external_dirs:
   - !secret snapshot_location

# Enables the frontend
frontend:
 themes: !include_dir_merge_named themes

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
 reporting: false

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# Enables support for tracking state changes over time
#history:

# View all events in a logbook
#logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Weather prediction
sensor: !include_dir_list sensors

# Text to speech
#tts:
#  - platform: google

# Logger
#logger:
# default: error
# logs:
#  homeassistant.components.shell_command: debug

system_log:
 fire_event: true

group: !include_dir_merge_named groups
automation: !include_dir_merge_list automations
script: !include_dir_list scripts
device_tracker: !include_dir_list device_tracker
zone: !include_dir_list zones

#mqtt:
# broker: core-mosquitto
# username: !secret mqtt_user
# password: !secret mqtt_password

panel_custom:
 - name: floorplan
   sidebar_title: Floorplan
   sidebar_icon: mdi:home
   url_path: floorplan
   config: !include floorplan.yaml

telegram_bot:
 - platform: polling
   api_key: !secret telegram_bot_api_key
   allowed_chat_ids:
    - !secret alex_telegram_chat_id

notify: !include_dir_list notify-platforms

zwave:
 usb_path: /dev/ttyACM0
 network_key: !secret zwave_key
 polling_interval: 30000

switch:
 - platform: tplink
   name: Power socket 1
   host: 192.168.178.69

camera: !include_dir_merge_named cameras

input_boolean: !include_dir_merge_named input_booleans

influxdb:
  host: localhost
  port: 8086
  database: homeassistant
  username: homeassistant
  password: !secret influx_db_password
  max_retries: 3
  default_measurement: state
  exclude:
   entities:
    - sensor.fritz_netmonitor
   domains:
    - automation
    - camera
    - group
    - media_player
    - updater
    - persistent_notification
    - sun
    - switch
    - zone
    - zwave

panel_iframe: !include_dir_merge_named iframe_panels

binary_sensor: !include_dir_merge_named binarysensors

shell_command: !include_dir_merge_named shellcommands

lovelace:
  mode: yaml

alarm_control_panel:
  - platform: manual
    name: Home Alarm
    code: !secret alarm_code
    pending_time: 30
    delay_time: 30
    trigger_time: 30
    disarmed:
      trigger_time: 0
    armed_home:
      pending_time: 0
      delay_time: 0