homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret time_zone
  # Customization file
  customize: !include customize.yaml
  whitelist_external_dirs:
    - /share/motioneye

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes

# Enables configuration UI
config:

system_health:

scene: !include scenes.yaml

api:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  reporting: false

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# Enables support for tracking state changes over time
#history:

# View all events in a logbook
#logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Weather prediction
weather:
  - platform: darksky
    api_key: !secret darksky_api_key

sensor: !include_dir_list sensors

# Text to speech
#tts:
#  - platform: google

# Logger
#logger:
# default: error
# logs:
#  homeassistant.components.shell_command: debug

system_log:
  fire_event: true

group: !include_dir_merge_named groups
automation: !include_dir_merge_list automations
script: !include_dir_list scripts
device_tracker: !include_dir_list device_tracker
zone: !include_dir_list zones

panel_custom:
  - name: floorplan
    sidebar_title: Floorplan
    sidebar_icon: mdi:home
    url_path: floorplan
    config: !include floorplan.yaml

telegram_bot:
  - platform: polling
    api_key: !secret telegram_bot_api_key
    allowed_chat_ids:
      - !secret alex_telegram_chat_id

notify: !include_dir_list notify-platforms

zwave:
  usb_path: /dev/ttyACM0
  network_key: !secret zwave_key
  polling_interval: 30000

switch: !include_dir_list switches

camera: !include_dir_list cameras

input_boolean: !include_dir_merge_named input_booleans

recorder:
  purge_keep_days: 1
  exclude:
    entities:
      - sensor.fritz_netmonitor
    domains:
      - automation
      - camera
      - group
      - media_player
      - updater
      - persistent_notification
      - sun
      - switch
      - weather
      - zone
      - zwave

influxdb:
  host: localhost
  port: 8086
  database: homeassistant
  username: homeassistant
  password: !secret influx_db_password
  max_retries: 3
  default_measurement: state
  exclude:
    entities:
      - sensor.fritz_netmonitor
    domains:
      - automation
      - camera
      - group
      - media_player
      - updater
      - persistent_notification
      - sun
      - switch
      - weather
      - zone
      - zwave

panel_iframe: !include_dir_merge_named iframe_panels

binary_sensor: !include_dir_list binarysensors

shell_command: !include_dir_merge_named shellcommands

alarm_control_panel:
  - platform: manual
    name: Home Alarm
    code: !secret alarm_code
    delay_time: 0
    trigger_time: 0
    disarmed:
      trigger_time: 0
    armed_home:
      delay_time: 0

fritzbox:
  devices:
    - host: 192.168.179.1
      username: smart
      password: a1b2c3d4

input_text: !include_dir_merge_named input_texts

circadian_lighting:
  interval: 60
  transition: 60

fan: !include_dir_merge_named fans

plant: !include_dir_merge_named plants

media_player: !include_dir_merge_named media_players

input_number: !include_dir_merge_named input_numbers

intent_script: !include intents/intents.yaml

hacs:
  token: !secret hacs_token

# Example configuration.yaml entry
neato:
  username: !secret neato_user
  password: !secret neato_pass

mobile_app:

ssdp:

folder_watcher:
  - folder: /share/motioneye
    patterns:
      - "*.thumb"
