- platform: pi_hole
  monitored_conditions:
   - ads_blocked_today
   - ads_percentage_today
   - unique_clients
   - clients_ever_seen
- platform: yr
- platform: systemmonitor
  resources:
   - type: disk_use_percent
   - type: memory_use_percent
   - type: disk_use
   - type: processor_use