title: Smart home overview
views: 
 - title: Main
   path: main
   cards:
    - type: weather-forecast
      entity: weather.dark_sky
      name: Weather
    - type: glance
      title: Pi
      entities:
       - entity: sensor.cpu_temperature
         name: CPU temperature
         icon: mdi:raspberrypi
       - entity: sensor.disk_use_percent_
         name: Disk usage
         icon: mdi:micro-sd
       - entity: sensor.processor_use
         name: CPU usage
         icon: mdi:memory
       - entity: sensor.memory_use_percent
         name: RAM usage
         icon: mdi:memory
 - title: Alarm
   path: alarm
   cards:
    - type: alarm-panel
      entity: alarm_control_panel.home_alarm
 - title: Surveillance
   path: surveillance
   cards:
    - type: picture-entity
      entity: camera.cam_0
      name: Room
      show_state: false
 - title: Bathroom
   cards:
    - type: glance
      title: Bathroom
      entities:
       - entity: binary_sensor.aeotec_zw100_multisensor_6_sensor
         name: Movement
         icon: mdi:walk
       - entity: sensor.aeotec_zw100_multisensor_6_relative_humidity
         name: Humidity
         icon: mdi:water-percent
       - entity: sensor.aeotec_zw100_multisensor_6_luminance
         name: Luminance
         icon: mdi:weather-sunny
       - entity: sensor.aeotec_zw100_multisensor_6_temperature
         name: Temperature
         icon: mdi:thermometer