- alias: Neato cleaning finished
  trigger:
   - platform: state
     entity_id: vacuum.neato
     from: cleaning
     to: docked
  action:
   service: switch.turn_off
   data:
    entity_id: switch.hallway_devices