- alias: Neato start cleaning
  trigger:
   - platform: time
     at: '08:00:00'
  condition:
   - condition: state
     entity_id: binary_sensor.workday_sensor
     state: 'on'
  action:
   service: vacuum.start
   data:
    entity_id: vacuum.neato