- alias: Set eco when not home
  trigger:
   - platform: state
     entity_id: group.persons
     to: 'not home'
  action:
    - service: climate.set_operation_mode
      data:
        entity_id: "all"
        operation_mode: eco