- alias: Set heat when home
  trigger:
   - platform: state
     entity_id: group.persons
     to: 'home'
  action:
    - service: climate.set_operation_mode
      data:
        entity_id: "all"
        operation_mode: heat