- alias: Turn off heating when not home
  trigger:
   - platform: state
     entity_id: group.persons
     to: 'not_home'
  action:
    - service: climate.turn_off
      data:
        entity_id: "all"