- alias: Turn on when heating enabled
  trigger:
    - platform: state
      entity_id: binary_sensor.heating_enabled
      to: "on"
    - platform: state
      entity_id:
        - input_boolean.air_mode
    - platform: state
      entity_id:
        - sensor.desired_temperature
  condition:
    - condition: state
      entity_id: group.persons
      state: "home"
    - condition: state
      entity_id:
        - input_boolean.air_mode
      state: "off"
  action:
    - service: climate.set_temperature
      data_template:
        {
          "entity_id": "all",
          "temperature": "{{ states.sensor.desired_temperature.state | float }}",
        }
