- alias: Turn off living area
  trigger:
   - platform: state
     entity_id: binary_sensor.livingarea_light_toggle
     to: 'off'
  action:
   service: light.turn_off
   data:
    entity_id: light.livingarea