- alias: Turn on living area
  trigger:
   - platform: state
     entity_id: binary_sensor.rli_emu_00_smo
     to: 'on'
   - platform: state
     entity_id: sensor.rli_emu_00_slu
   - platform: state
     entity_id: media_player.samsung_tv_remote
  condition:
   condition: template
   value_template: "
   {{
     is_state('group.persons','home') and
     states('sensor.average_apartment_luminance') | float <= states('input_number.light_threshold') | float and 
     (is_state('input_text.last_movement','Living area') or is_state('binary_sensor.rli_emu_00_smo','on')) and
     is_state('media_player.samsung_tv','off') and
     is_state('binary_sensor.sleep','off')
   }}"
  action:
   service: light.turn_on
   data:
    entity_id: light.livingarea