- alias: "Telegram disarm alarm"
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      data: "/disarmAlarm"
  action:
    service: alarm_control_panel.alarm_disarm
    entity_id: alarm_control_panel.home_alarm
    data:
      code: !secret alarm_code
