- alias: 'Send motion captures to telegram'
  trigger:
    platform: event
    event_type: folder_watcher
    event_data: 
      event_type: created
  action:
    - service: telegram_bot.send_video
      data_template:
        file: "{{ trigger.event.data.path|regex_replace(find='.thumb', replace='', ignorecase=False) }}"
        timeout: 1000