- alias: 'sleep mode updated'
  trigger:
    - platform: state
      entity_id: variable.sleep_mode
  action:
    - service: notify.alex_telegram   
      data_template:   
        message: 'Sleep mode changed to {{ trigger.to_state.state }}'