- alias: Turn off toilet awake
  trigger:
    - platform: state
      entity_id: binary_sensor.zw100_multisensor_6_home_security_motion_detected
      to: 'off'
      for:
        seconds: 20
    - platform: state
      entity_id: input_text.last_movement
  condition:
    - condition: template
      value_template: "{{ not is_state('input_text.last_movement', 'Toilet') }}"
    - condition: state
      entity_id: binary_sensor.zw100_multisensor_6_home_security_motion_detected
      state: 'off'
    - condition: state
      entity_id: input_boolean.sleep_mode
      state: 'off' 
  action:
    service: light.turn_off
    data:
      entity_id: light.toilet
      transition: 10