- alias: Turn on toilet
  trigger:
   - platform: state
     entity_id: binary_sensor.toilet_light_toggle
     to: 'on'
  condition:
   condition: state
   entity_id: group.persons
   state: 'home'
  action:
   service: light.turn_on
   data:
    entity_id: light.toilett