- alias: Turn on toilet
  trigger:
    - platform: state
      entity_id: binary_sensor.zw100_multisensor_6_home_security_motion_detected
      to: 'on'
  condition:
    - condition: state
      entity_id: group.persons
      state: 'home'
  action:
    service: light.turn_on
    data:
      entity_id: light.toilet