- alias: weekly backup
  id: weekly_backup
  trigger:
   platform: time
   at: '23:00:00'
  condition:
   condition: time
   weekday: 
    - mon
  action:
   - service: hassio.snapshot_full
     data_template:
      name: Automated Backup {{ now().strftime('%Y-%m-%d') }}
   - delay: '00:01:30'
   - service: hassio.addon_stdin
     data_template:
      addon: 7be23ff5_dropbox_sync
      input: {"command":"upload"}