- alias: cpu above threshold
  id: cpu_above_threshold
  trigger:
   platform: numeric_state
   entity_id: sensor.processor_use
   above: 30
   for:
    minutes: 30
  action:
   - service: notify.alex_telegram
     data_template:
      message: 'CPU usage above threshold since 30 minutes. HALP!'