- alias: notify on errors
  trigger:
   platform: event
   event_type: system_log_event
   event_data:
    level: ERROR
  action:
   - service: notify.alex_telegram
     data_template:
      message: 'Error: {{ trigger.event.data.message }}'