- alias: notify on errors
  trigger:
   platform: event
   event_type: system_log_event
   event_data:
    level: ERROR
  condition:
   - condition: state
     entity_id: input_boolean.error_reporting
     state: 'on'
  action:
   - service: notify.alex_telegram
     data_template:
      message: 'Error: {{ trigger.event.data.message }}'