- alias: Someone is at home
  trigger:
   platform: state
   entity_id: group.persons
   from: 'not_home'
   to: 'home'
  action:
   - service: notify.alex_telegram
     data:
      message: 'Welcome back home. Entering presence mode.'