- alias: activate standby mode after 10 minutes
  trigger:
   platform: state
   entity_id: group.persons
   from: 'home'
   to: 'not_home'
   for:
    minutes: 10
  action:
   - service: notify.alex_telegram
     data:
      message: 'Nobody at home since 10 minutes. Entering stand by mode.'