- alias: send image of detected movement
  trigger:
   platform: state
   entity_id: binary_sensor.aeotec_zw100_multisensor_6_sensor_3
   to: 'on'
  action:
   - service: camera.snapshot
     data:
      entity_id: camera.cam_0
      filename: /share/snapshots/cam0.png
   - service: telegram_bot.send_photo
     data:
      file: /share/snapshots/cam0.png