blueprint:
  name: Turns light on or off based on persons at home, sun elevation, motion, last movement, sleep, media playing, door open/closed.
  domain: automation
  input:
    room_name:
      name: Name of the room
    light:
      name: Light(s) to control
      selector:
        target:
          entity:
            domain: light
    last_room_movement:
      name: Last room with detected movement (optional)
      default:
      selector:
        entity:
          domain: input_text
    motion_sensor:
      name: Motion sensor
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
    persons:
      name: Persons
      selector:
        entity:
          domain: group
    sleep:
      name: Sleep boolean (optional)
      default:
      selector:
        entity:
          domain: input_boolean
    sleep_light_on:
      name: Turn on light when sleep 'true'
      default: false
      selector:
        boolean: {}
    light_transition_awake:
      name: Light transition when awake
      description: Time in seconds
      default: 10
      selector:
        number:
          min: 0.0
          max: 100
          mode: slider
          step: 1.0
    light_transition_sleep:
      name: Light transition when asleep
      description: Time in seconds
      default: 0
      selector:
        number:
          min: 0.0
          max: 100
          mode: slider
          step: 1.0
    sun_elevation:
      name: Highest elevation for artificial light
      description: If elevation is above this value, light will be turned off
      default: 5
      selector:
        number:
          min: -5
          max: 10
          mode: slider
          step: 0.5
    media_player:
      name: Media player (optional)
      description: Turns off the light when state is 'playing'
      default:
      selector:
        entity:
          domain: media_player
    door_sensor:
      name: Door sensor (optional)
      default:
      selector:
        target:
          entity:
            domain: binary_sensor
            device_class: door
    door_light_behavior:
      name: Light behavior when door is closed
      description: When 'true' light will be turned off, when door is closed. When 'false' light will be turned on, when door is open.
      default: false
      selector:
        boolean: {}

variables:
  sun_elevation_value: !input sun_elevation
  door_light_behavior_value: !input door_light_behavior
  light_transition_awake_value: !input light_transition_awake
  light_transition_sleep_value: !input light_transition_sleep
  last_room_movement_value: !input last_room_movement
  room_name_value: !input room_name
  sleep_light_on_value: !input sleep_light_on
  motion_sensor_value: !input motion_sensor
  sleep_value: !input sleep
  persons_value: !input persons
  sun_elevation_condition: '{{ ((state_attr(''sun.sun'',''elevation'') | float) <= (sun_elevation_value | float)) }}'
#  media_player_condition: '{{ media_player == none or states[media_player].state != ''playing'' }}'
#  door_sensor_condition: '{{ door_sensor == none or (states[door_sensor].state == ''on'' ) == door_light_behavior_value }}'
  light_transition_value: '{{ light_transition_awake_value if (states[sleep_value].state == ''on'') else light_transition_sleep_value }}'
  last_room_movement_condition: '{{ last_room_movement_value == none or last_room_movement_value != room_name_value }}'
  persons_home_condition: '{{ states[persons_value].state == ''home'' }}'
  sleep_light_condition: '{{ sleep_value == none or states[sleep_value].state == ''off'' or (states[sleep_value].state == ''on'') == sleep_light_on_value }}'
  motion_condition: '{{ states[motion_sensor_value].state == ''on'' }}'

trigger:
  - platform: state
    entity_id: !input last_room_movement
  - platform: state
    entity_id: !input motion_sensor
  - platform: state
    entity_id: sun.sun
# it is currently not possible to use null triggers. so i have to settle with these.

action:
  - choose:
    - conditions:
      - '{{ sun_elevation_condition }}'
#      - '{{ media_player_condition }}'
#      - '{{ door_sensor_condition }}'
      - '{{ persons_home_condition }}'
      - '{{ sleep_light_condition }}'
      - '{{ motion_condition }}'
      sequence:
      - service: light.turn_on
        target: !input light
      - service: input_text.set_value
        data: 
          entity_id: !input last_room_movement
          value: !input room_name
      - wait_for_trigger:
        platform: state
        entity_id: !input motion_sensor
        from: 'on'
        to: 'off'
    - conditions:
      - '{{ last_room_movement_condition }}'
      sequence:
      - service: light.turn_off
        target: !input light
        data:
          transition: '{{ light_transition_value }}'
#    - conditions:
#      - '{{ not persons_home_condition }}'
#      sequence:
#      - service: light.turn_off
#        target: !input light