- alias: Bathroom movement
  trigger:
   - platform: state
     entity_id: binary_sensor.rba_emu_smo
     to: 'on'
  condition:
   - condition: template
     value_template: "{{ is_state('binary_sensor.sleep','off') }}"
  action:
   - service: input_text.set_value
     data:
      entity_id: input_text.last_movement
      value: 'Bathroom'