- alias: Bathroom movement
  trigger:
   - platform: state
     entity_id: binary_sensor.zw100_multisensor_6_home_security_motion_detected_5
     to: 'on'
  condition:
   - condition: template
     value_template: "{{ is_state('input_boolean.sleep_mode','off') }}"
  action:
   - service: input_text.set_value
     data:
      entity_id: input_text.last_movement
      value: 'Bathroom'