- alias: Bedroom movement
  trigger:
   - platform: state
     entity_id: binary_sensor.zw100_multisensor_6_home_security_motion_detected_4
     to: 'on'
  action:
   - service: input_text.set_value
     data:
      entity_id: input_text.last_movement
      value: 'Bedroom'