- alias: Hallway movement
  trigger:
   - platform: state
     entity_id: binary_sensor.rha_emu_smo
     to: 'on'
  action:
   - service: input_text.set_value
     data:
      entity_id: input_text.last_movement
      value: 'Hallway'