- alias: Turn off hallway awake
  trigger:
   - platform: state
     entity_id: binary_sensor.rha_emu_smo
     to: 'off'
   - platform: state
     entity_id: sensor.average_apartment_luminance
   - platform: state
     entity_id: binary_sensor.rha_edo
     to: 'off'
     for: 
      minutes: 2
  condition:
   - condition: state
     entity_id: binary_sensor.rha_edo
     state: 'off'
   - condition: template
     value_template: "
  {{
    is_state('input_boolean.sleep_mode','off') and
    (states('sensor.average_apartment_luminance') | float > states('input_number.light_threshold') | float or 
    is_state('binary_sensor.rha_emu_smo', 'off'))
  }}"
  action:
   service: light.turn_off
   data:
    entity_id: light.hallway0, light.hallway1
    transition: 10