- alias: Turn on hallway
  trigger:
    - platform: state
      entity_id: binary_sensor.zw100_multisensor_6_home_security_motion_detected_3
      to: 'on'
  condition:
    - condition: state
      entity_id: group.persons
      state: 'home'
    - condition: template
      value_template: "
      {{
        is_state('binary_sensor.artificial_light','on')
      }}"
  action:
    service: light.turn_on
    data:
      entity_id: light.hallway0, light.hallway1