- alias: Turn on hallway
  trigger:
   - platform: state
     entity_id: binary_sensor.rha_emu_smo
     to: 'on'
  condition:
   - condition: state
     entity_id: group.persons
     state: 'home'
   - condition: template
     value_template: "
  {{
    states('sensor.average_apartment_luminance') | float <= states('input_number.light_threshold') | float
  }}"
  action:
   service: light.turn_on
   data:
    entity_id: light.hallway0, light.hallway1