- alias: Turn off hallway sleep
  trigger:
    - platform: state
      entity_id: binary_sensor.zw100_multisensor_6_home_security_motion_detected_3
      to: 'off'
  condition:
    - condition: template
      value_template: "
  {{
    is_state('input_boolean.sleep_mode','on') and
    is_state('binary_sensor.zw100_multisensor_6_home_security_motion_detected_3', 'off')
  }}"
  action:
    service: light.turn_off
    data:
      entity_id: light.hallway0, light.hallway1