- alias: Turn on hallway when door is open
  trigger:
    - platform: state
      entity_id: binary_sensor.zw112_door_window_sensor_6_sensor_2
      to: 'on'
  condition:
    condition: state
    entity_id: binary_sensor.artificial_light
    state: 'on'
  action:
    service: light.turn_on
    data:
      entity_id: light.hallway0, light.hallway1