- alias: Turn on bathroom
  trigger:
    - platform: state
      entity_id: binary_sensor.rba_emu_smo
      to: 'on'
    - platform: state
      entity_id: sensor.rba_emu_slu
    - platform: state
      entity_id: binary_sensor.artificial_light
  condition:
    condition: template
    value_template: "
    {{
      is_state('group.persons','home') and
      is_state('binary_sensor.artificial_light','on') and 
      (is_state('input_text.last_movement','Bathroom') or is_state('binary_sensor.rba_emu_smo','on')) and
      is_state('input_boolean.sleep_mode','off')
    }}"
  action:
    service: light.turn_on
    data:
      entity_id: light.bathroom