- alias: Turn on bathroom
  trigger:
   - platform: state
     entity_id: binary_sensor.rba_emu_smo
     to: 'on'
   - platform: state
     entity_id: sensor.rba_emu_slu
  condition:
   condition: template
   value_template: "
   {{
     is_state('group.persons','home') and
     states('sensor.average_apartment_luminance') | float <= states('input_number.light_threshold') | float and 
     (is_state('input_text.last_movement','Bathroom') or is_state('binary_sensor.rba_emu_smo','on')) and
     is_state('binary_sensor.sleep','off')
   }}"
  action:
   service: light.turn_on
   data:
    entity_id: light.bathroom