- alias: Turn off bathroom
  trigger:
   - platform: state
     entity_id: binary_sensor.rba_emu_smo
     to: 'off'
   - platform: numeric_state
     entity_id: sensor.rba_emu_slu
     above: 50
  action:
   service: light.turn_off
   data:
    entity_id: light.bathroom