- alias: Turn off bathroom
  trigger:
   - platform: state
     entity_id: binary_sensor.bathroom_light_toggle
     to: 'off'
  action:
   service: light.turn_off
   data:
    entity_id: light.bathroom