- alias: Set heat when shower off
  trigger:
   - platform: state
     entity_id: binary_sensor.bathroom_humidity_rising
     to: 'off'
  condition:
   - condition: state
     entity_id: group.persons
     state: 'home'
  action:
    - service: climate.set_operation_mode
      data:
        entity_id: "climate.bathroom"
        operation_mode: heat