- alias: Turn on bathroom
  trigger:
   - platform: state
     entity_id: binary_sensor.rki_emu_smo
     to: 'on'
  condition:
   - condition: state
     entity_id: group.persons
     state: 'home'
   - condition: numeric_state
     entity_id: sensor.rki_emu_slu
     below: 50
  action:
   service: light.turn_on
   data:
    entity_id: light.kitchen