- alias: Turn off kitchen
  trigger:
    - platform: state
      entity_id: binary_sensor.rki_emu_smo
      to: 'off'
    - platform: state
      entity_id: sensor.average_apartment_luminance
    - platform: state
      entity_id: input_text.last_movement
    - platform: state
      entity_id:
        - binary_sensor.artificial_light      
  condition:
    - condition: template
      value_template: "
  {{
    is_state('binary_sensor.artificial_light','off') or 
    (not is_state('input_text.last_movement', 'Kitchen') and is_state('binary_sensor.rki_emu_smo', 'off'))
  }}"  
  action:
    service: light.turn_off
    data_template:
      entity_id: light.kitchen
      transition: >
            {% if states.switch.circadian_lighting_circadian_lighting.attributes["brightness"] | int >= 10 %}
              10
            {% else %}
              1
            {% endif %}