- alias: Turn on hallway devices switch
  trigger:
   - platform: time
     at: '06:00:00'
  condition:
   - condition: state
     entity_id: binary_sensor.workday_sensor
     state: 'on'
  action:
   service: switch.turn_on
   data:
    entity_id: switch.hallway_devices