- alias: Turn off entertainment when away or asleep
  trigger:
    - platform: state
      entity_id: input_boolean.sleep_mode
      to: 'on'
    - platform: state
      entity_id: group.persons
      to: 'not_home'
  action:
    - service: switch.turn_off
      entity_id: switch.entertainment_mode_switch