- alias: Turn off computer when away or asleep
  trigger:
    - platform: state
      entity_id: input_boolean.sleep_mode
      to: 'on'
    - platform: state
      entity_id: group.persons
      to: 'not_home'
      for: '0:20:00'
  condition:
    - condition: state
      entity_id: input_boolean.turn_off_computer
      state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.computer