- alias: Turn off switches
  trigger:
   - platform: state
     entity_id: binary_sensor.sleep
     to: 'on'
   - platform: state
     entity_id: group.persons
     to: 'not_home'
  action:
   service: switch.turn_off
   data:
    entity_id: switch.computer, switch.entertainment, switch.dehumidifier