- alias: Turn off bedroom
  trigger:
   - platform: state
     entity_id: binary_sensor.rbe_emu_smo
     to: 'off'
     for:
      seconds: 20
   - platform: state
     entity_id: sensor.average_apartment_luminance
   - platform: state
     entity_id: input_text.last_movement
  condition:
   - condition: template
     value_template: "
  {{
    states('sensor.average_apartment_luminance') | float > states('input_number.light_threshold') | float or 
    (not is_state('input_text.last_movement', 'Bedroom') and is_state('binary_sensor.rbe_emu_smo', 'off'))
  }}"  
  action:
   service: light.turn_off
   data_template:
    entity_id: light.bedroom
    transition: >
            {% if states.switch.circadian_lighting_circadian_lighting.attributes["brightness"] | int >= 10 %}
              10
            {% else %}
              1
            {% endif %}