- alias: Turn off bedroom
  trigger:
   - platform: state
     entity_id: binary_sensor.rbe_emu_smo
     to: 'off'
   - platform: numeric_state
     entity_id: sensor.rbe_emu_slu
     above: 45
  action:
   service: light.turn_off
   data:
    entity_id: light.bedroom