- alias: Turn on bedroom
  trigger:
   - platform: state
     entity_id: binary_sensor.rbe_emu_smo
     to: 'on'
  condition:
   - condition: state
     entity_id: group.persons
     state: 'home'
   - condition: numeric_state
     entity_id: sensor.rbe_emu_slu
     below: 45
  action:
   service: light.turn_on
   data:
    entity_id: light.bedroom