- alias: begin sleep mode
  trigger:
   platform: event
   event_type: telegram_command
   event_data:
    command: '/sleep'
  action:
   - service: input_boolean.toggle
     data:
      entity_id: input_boolean.sleep_mode